language: java

jdk:
  - oraclejdk8

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test cobertura:cobertura jacoco:report coveralls:report